language: python
python:
 - "3.6"
cache: pip
install:
    - pip install -r requirements.txt
    - pip install python-coveralls
    - pip install pytest
    - pip install pytest-cov
    - pip install coveralls
script:
        - pytest --cov=tests
after_success:
    - coveralls        
